//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public int IdHospitals { get; set; }
        public int IdProffessions { get; set; }
        public int IdDoctors { get; set; }
        public int IdTime { get; set; }
        public int IdUsers { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Hospitals Hospitals { get; set; }
        public virtual Proffessions Proffessions { get; set; }
        public virtual Time Time { get; set; }
    }
}
