//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdDoctorTime { get; set; }
    
        public virtual Authorization Authorization { get; set; }
        public virtual DoctorTime DoctorTime { get; set; }
    }
}
